import './globals.css';
import { Providers } from './providers';
import type { Metadata } from 'next';
import { Oswald } from 'next/font/google';
import Navbars from './Components/Navbar';
import NextQueryClient from './QueryClient';
import { Toaster } from 'react-hot-toast';

const oswald = Oswald({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Crud',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={oswald.className}>
        <Navbars />
        <NextQueryClient>
          <Providers>
            <main>
              {children}
              <Toaster />
            </main>
          </Providers>
        </NextQueryClient>
      </body>
    </html>
  );
}
